
project_id = "hrhvliqkmetcdphnetxb"

[api]
port = 54321
openapi_file = "api/openapi.json"

[functions]
[functions.create-coinpayments-payment]
verify_jwt = true
[functions.validate-api-keys]
verify_jwt = true
[functions.stripe-webhooks]
verify_jwt = false
[functions.get-coinpayments-currencies]
verify_jwt = true
