
project_id = "hrhvliqkmetcdphnetxb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:5173"

[analytics]
enabled = false

[experimental.functions.coinpayments-ipn-webhook]
verify_jwt = false

[experimental.functions.test-ipn-notification]
verify_jwt = false

[experimental.functions.validate-api-keys]
verify_jwt = false

[experimental.functions.test-ipn-webhook]
verify_jwt = false
