
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Add process polyfill for browser environment to fix "process is not defined" error
if (typeof window !== 'undefined' && !window.process) {
  window.process = { env: { NODE_ENV: 'development' } };
}

const SUPABASE_URL = "https://hrhvliqkmetcdphnetxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyaHZsaXFrbWV0Y2RwaG5ldHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNzAxMjcsImV4cCI6MjA1ODc0NjEyN30.n4mncbTJGzcPdEl0RqPFMo_UGOZI6D-GolKqFH6GJug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
